export const Errors = {
  EMPTY_PUBLIC_KEYS_LIST: "EmptyPublicKeysList",
  INVALID_PUBLIC_KEYS_LENGTH: "InvalidPublicKeyLength",
  PUBLIC_KEYS_SHARES_LENGTH_MISMATCH: "PublicKeysSharesLengthMismatch",
  VALIDATOR_ALREADY_EXISTS_WITH_DATA: "ValidatorAlreadyExistsWithData",
  INCORRECT_VALIDATOR_STATE_WITH_DATA: "IncorrectValidatorStateWithData",
  VALIDATOR_DOES_NOT_EXIST: "ValidatorDoesNotExist",
  INVALID_OPERATOR_IDS_LENGTH: "InvalidOperatorIdsLength",
  UNSORTED_OPERATORS_LIST: "UnsortedOperatorsList",
  OPERATORS_LIST_NOT_UNIQUE: "OperatorsListNotUnique",
  CLUSTER_IS_LIQUIDATED: "ClusterIsLiquidated",
  CLUSTER_DOES_NOT_EXISTS: "ClusterDoesNotExists",
  INCORRECT_CLUSTER_VERSION: "IncorrectClusterVersion",
  INCORRECT_CLUSTER_STATE: "IncorrectClusterState",
  CALLER_NOT_WHITELISTED: "CallerNotWhitelistedWithData",
  OPERATOR_VALIDATORS_LIMIT_EXCEEDED: "ExceedValidatorLimitWithData",
  INSUFFICIENT_BALANCE: "InsufficientBalance",
  FEE_TOO_LOW: "FeeTooLow",
  FEE_TOO_HIGH: "FeeTooHigh",
  OPERATOR_ALREADY_EXISTS: "OperatorAlreadyExists",
  OPERATOR_DOES_NOT_EXIST: "OperatorDoesNotExist",
  CALLER_NOT_OWNER: "CallerNotOwnerWithData",
  INVALID_WHITELIST_ADDRESSES_LENGTH: "InvalidWhitelistAddressesLength",
  ZERO_ADDRESS_NOT_ALLOWED: "ZeroAddressNotAllowed",
  INVALID_WHITELISTING_CONTRACT: "InvalidWhitelistingContract",
} as const;
