export const Errors = {
  EMPTY_PUBLIC_KEYS_LIST: "EmptyPublicKeysList",
  INVALID_PUBLIC_KEYS_LENGTH: "InvalidPublicKeyLength",
  PUBLIC_KEYS_SHARES_LENGTH_MISMATCH: "PublicKeysSharesLengthMismatch",
  VALIDATOR_ALREADY_EXISTS_WITH_DATA: "ValidatorAlreadyExistsWithData",
  INCORRECT_VALIDATOR_STATE_WITH_DATA: "IncorrectValidatorStateWithData",
  VALIDATOR_DOES_NOT_EXIST: "ValidatorDoesNotExist",
  INVALID_OPERATOR_IDS_LENGTH: "InvalidOperatorIdsLength",
  UNSORTED_OPERATORS_LIST: "UnsortedOperatorsList",
  OPERATORS_LIST_NOT_UNIQUE: "OperatorsListNotUnique",
  CLUSTER_IS_LIQUIDATED: "ClusterIsLiquidated",
  CLUSTER_DOES_NOT_EXISTS: "ClusterDoesNotExists",
  CLUSTER_NOT_LIQUIDATABLE: "ClusterNotLiquidatable",
  CLUSTER_ALREADY_ENABLED: "ClusterAlreadyEnabled",
  INCORRECT_CLUSTER_VERSION: "IncorrectClusterVersion",
  INCORRECT_CLUSTER_STATE: "IncorrectClusterState",
  CALLER_NOT_WHITELISTED: "CallerNotWhitelistedWithData",
  OPERATOR_VALIDATORS_LIMIT_EXCEEDED: "ExceedValidatorLimitWithData",
  INSUFFICIENT_BALANCE: "InsufficientBalance",
  FEE_TOO_LOW: "FeeTooLow",
  FEE_TOO_HIGH: "FeeTooHigh",
  FEE_EXCEEDS_INCREASE_LIMIT: "FeeExceedsIncreaseLimit",
  NO_FEE_DECLARED: "NoFeeDeclared",
  SAME_FEE_CHANGE_NOT_ALLOWED: "SameFeeChangeNotAllowed",
  FEE_INCREASE_NOT_ALLOWED: "FeeIncreaseNotAllowed",
  OPERATOR_ALREADY_EXISTS: "OperatorAlreadyExists",
  OPERATOR_DOES_NOT_EXIST: "OperatorDoesNotExist",
  CALLER_NOT_OWNER: "CallerNotOwnerWithData",
  INVALID_WHITELIST_ADDRESSES_LENGTH: "InvalidWhitelistAddressesLength",
  ZERO_ADDRESS_NOT_ALLOWED: "ZeroAddressNotAllowed",
  INVALID_WHITELISTING_CONTRACT: "InvalidWhitelistingContract",
  SAME_FEE_CHANGE_NOW_ALLOWED: "SameFeeChangeNotAllowed",
  APPROVAL_NOT_WITHIN_TIMEFRAME: "ApprovalNotWithinTimeframe",
  OWNABLE_CALLER_NOT_OWNER: "Ownable: caller is not the owner",
  NEW_BLOCK_PERIOD_IS_BELOW_MINIMUM: "NewBlockPeriodIsBelowMinimum",
  CLUSTER_DOES_NOT_EXIST: "ClusterDoesNotExists",
  INCORRECT_VALIDATOR_STATE: "IncorrectValidatorStateWithData",
  STAKE_TOO_LOW: "StakeTooLow",
  ZERO_AMOUNT: "ZeroAmount",
  COOLDOWN_ACTIVE: "CooldownActive",
  UNSTAKE_AMOUNT_EXCEEDS_BALANCE: "UnstakeAmountExceedsBalance",
  ROOT_NOT_FOUND: "RootNotFound",
  // DAO errors
  NOT_ORACLE: "NotOracle",
  STALE_BLOCK_NUMBER: "StaleBlockNumber",
  FUTURE_BLOCK_NUMBER: "FutureBlockNumber",
  ALREADY_VOTED: "AlreadyVoted",
  ZERO_ADDRESS: "ZeroAddress",
  ORACLE_ALREADY_ASSIGNED: "OracleAlreadyAssigned",
  INVALID_QUORUM: "Invalid quorum",
} as const;
