export const Events = {
  VALIDATOR_ADDED: "ValidatorAdded",
  VALIDATOR_REMOVED: "ValidatorRemoved",
  VALIDATOR_EXITED: "ValidatorExited",
  CLUSTER_LIQUIDATED: "ClusterLiquidated",
  CLUSTER_REACTIVATED: "ClusterReactivated",
  CLUSTER_DEPOSITED: "ClusterDeposited",
  CLUSTER_WITHDRAWN: "ClusterWithdrawn",
  CLUSTER_MIGRATED_TO_ETH: "ClusterMigratedToETH",
  OPERATOR_ADDED: "OperatorAdded",
  OPERATOR_PRIVACY_STATUS_UPDATED: "OperatorPrivacyStatusUpdated",
  OPERATOR_REMOVED: "OperatorRemoved",
  OPERATOR_MULTIPLE_WHITELIST_UPDATED: "OperatorMultipleWhitelistUpdated",
  OPERATOR_MULTIPLE_WHITELIST_REMOVED: "OperatorMultipleWhitelistRemoved",
  OPERATORS_WHITELISTING_CONTRACT_UPDATED: "OperatorWhitelistingContractUpdated",
  OPERATORS_PRIVACY_STATUS_UPDATED: "OperatorPrivacyStatusUpdated",
  OPERATOR_FEE_DECLARED: "OperatorFeeDeclared",
} as const;
