export const Events = {
  VALIDATOR_ADDED: "ValidatorAdded",
  VALIDATOR_REMOVED: "ValidatorRemoved",
  OPERATOR_ADDED: "OperatorAdded",
  OPERATOR_PRIVACY_STATUS_UPDATED: "OperatorPrivacyStatusUpdated",
  OPERATOR_REMOVED: "OperatorRemoved",
  OPERATOR_MULTIPLE_WHITELIST_UPDATED: "OperatorMultipleWhitelistUpdated",
  OPERATOR_MULTIPLE_WHITELIST_REMOVED: "OperatorMultipleWhitelistRemoved",
  OPERATORS_WHITELISTING_CONTRACT_UPDATED: "OperatorWhitelistingContractUpdated",
  OPERATORS_PRIVACY_STATUS_UPDATED: "OperatorPrivacyStatusUpdated",
  OPERATOR_FEE_DECLARED: "OperatorFeeDeclared",
  OPERATOR_FEE_DECLARATION_CANCELLED: "OperatorFeeDeclarationCancelled",
  OPERATOR_FEE_EXECUTED: "OperatorFeeExecuted",
  OPERATOR_WITHDRAWN: "OperatorWithdrawn",
  FEE_RECIPIENT_ADDRESS_UPDATED: "FeeRecipientAddressUpdated",
  OPERATOR_FEE_INCREASE_LIMIT_UPDATED: "OperatorFeeIncreaseLimitUpdated",
  DECLARE_OPERATOR_FEE_PERIOD_UPDATED: "DeclareOperatorFeePeriodUpdated",
  EXECUTE_OPERATOR_FEE_PERIOD_UPDATED: "ExecuteOperatorFeePeriodUpdated",
  LIQUIDATION_THRESHOLD_PERIOD_UPDATED: "LiquidationThresholdPeriodUpdated",
  LIQUIDATION_THRESHOLD_PERIOD_UPDATED_SSV: "LiquidationThresholdPeriodSSVUpdated",
  MINIMUM_LIQUIDATION_COLLATERAL_UPDATED: "MinimumLiquidationCollateralUpdated",
  MINIMUM_LIQUIDATION_COLLATERAL_UPDATED_SSV: "MinimumLiquidationCollateralSSVUpdated",
  OPERATOR_MAXIMUM_FEE_UPDATED: "OperatorMaximumFeeUpdated",
  OPERATOR_MAXIMUM_FEE_UPDATED_SSV: "OperatorMaximumFeeSSVUpdated",
  STAKED: "Staked",
  UNSTAKE_REQUESTED: "UnstakeRequested",
  UNSTAKE_WITHDRAWN: "UnstakedWithdrawn",
} as const;