name: Solidity code coverage

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Solidity code coverage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '22.x'
      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - run: npx hardhat test --coverage
        env:
          NO_GAS_ENFORCE: '1'
          COVERAGE: 'true'
