name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Verify Foundry
        run: forge --version

      - name: Install dependencies
        run: npm ci
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Compile contracts (Hardhat)
        run: npx hardhat compile --force

      - name: Run Slither
        uses: crytic/slither-action@v0.3.2
        id: slither
        env:
          FOUNDRY_PROFILE: slither
          PATH: /home/runner/.foundry/bin:${{ env.PATH }}
        with:
          fail-on: high
          target: contracts
          slither-args: --hardhat-ignore-compile --exclude controlled-delegatecall,incorrect-return --filter-paths "contracts/test/" --exclude-informational --exclude-dependencies
