name: Run tests

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Hardhat fork tests
    env:
      GH_TOKEN: ${{ secrets.github_token }}
      FORK_BLOCK_NUMBER: ${{ secrets.fork_block_number }}
      HOODI_RPC_URL: ${{ secrets.hoodi_rpc_url }}
      MAINNET_RPC_URL: ${{ secrets.mainnet_rpc_url }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      
      - name: Compile contracts
        run: npx hardhat compile
        env:
          FORK_BLOCK_NUMBER: ${{ secrets.fork_block_number }}
          HOODI_RPC_URL: ${{ secrets.hoodi_rpc_url }}

      - name: Run fork tests
        run: npx hardhat test test/test-forked/v2.0.0/fullIntegrationForked.test.ts
        env:
          REPORT_GAS: 'true'
          NO_GAS_ENFORCE: '1'
          FORK_BLOCK_NUMBER: ${{ secrets.fork_block_number }}
          HOODI_RPC_URL: ${{ secrets.hoodi_rpc_url }}
          MAINNET_RPC_URL: ${{ secrets.mainnet_rpc_url }}
